package com.example.demo.controllers;

import com.example.demo.entities.Equipment;
import com.example.demo.repositories.EquipmentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)

public class EquipmentController {
    @Autowired // This means to get the bean called equipmentRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EquipmentRepository equipmentRepository;

    @PostMapping(path = "/addEquipment") // Map ONLY POST Requests
    public @ResponseBody String addNewEquipment(@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Equipment e = new Equipment();
        e.setName(name);
        equipmentRepository.save(e);
        return "Saved";
    }

    @GetMapping(path = "/allEquipment")
    public @ResponseBody Iterable<Equipment> getAllEquipment() {
        // This returns a JSON or XML with the equipment
        return equipmentRepository.findAll();
    }
}
