package com.example.demo.controllers;

import com.example.demo.entities.Follow;
import com.example.demo.repositories.FollowRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)

public class FollowController {
    @Autowired // This means to get the bean called followRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FollowRepository followRepository;

    @PostMapping(path = "/addFollow") // Map ONLY POST Requests
    public @ResponseBody String addNewFollow(@RequestParam long follower, @RequestParam long followed) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Follow f = new Follow();
        f.setFollower(follower);
        f.setFollowed(followed);
        followRepository.save(f);
        return "Saved";
    }

    @GetMapping(path = "/allFollow")
    public @ResponseBody Iterable<Follow> getAllFollow() {
        // This returns a JSON or XML with the follows
        return followRepository.findAll();
    }
}
