package com.example.demo.controllers;

import com.example.demo.entities.Ingredient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class IngredientController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private com.example.demo.repositories.IngredientRepository ingredientRepository;

    @PostMapping(path = "/addIngredient") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestParam Integer ingredientID, @RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Ingredient i = new Ingredient();
        i.setIngredientID(ingredientID);
        i.setName(name);
        return "Saved";
    }

    @GetMapping(path = "/allIngredients")
    public @ResponseBody Iterable<Ingredient> getAllIngredients() {
        // This returns a JSON or XML with the users
        return ingredientRepository.findAll();
    }
}