package com.example.demo.controllers;

import com.example.demo.entities.PostEquipment;
import com.example.demo.repositories.PostEquipmentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class PostEquipmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PostEquipmentRepository postEquipmentRepository;

    @PostMapping(path = "/addPostEquipment") // Map ONLY POST Requests
    public @ResponseBody
    String addPostEquipment(@RequestParam Integer post, @RequestParam Integer equipment) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        PostEquipment pe = new PostEquipment();
        pe.setPost(post);
        pe.setEquipment(equipment);
        postEquipmentRepository.save(pe);
        return "Saved";
    }

    @GetMapping(path = "/allPostEquipment")
    public @ResponseBody Iterable<PostEquipment> getAllPostEquipment() {
        // This returns a JSON or XML with the users
        return postEquipmentRepository.findAll();
    }
}
