package com.example.demo.controllers;

import com.example.demo.entities.PostEquipment;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/p") // This means URL's start with /demo (after Application path)
public class PostEquipmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private com.example.demo.repositories.PostEquipmentRepository postEquipmentRepository;

    @PostMapping(path="/addPostEquipment") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam Integer post, @RequestParam Integer equipment) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        PostEquipment pe = new PostEquipment();
        pe.setPost(post);
        pe.setEquipment(equipment);
        return "Saved";
    }

    @GetMapping(path="/allPostEquipments")
    public @ResponseBody Iterable<PostEquipment> getAllPostEquipments() {
        // This returns a JSON or XML with the users
        return postEquipmentRepository.findAll();
    }
}
