package com.example.demo.controllers;

import com.example.demo.entities.PostCategory;
import com.example.demo.repositories.PostCategoryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class PostCategoryController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PostCategoryRepository postCategoryRepository;

    @PostMapping(path = "/addPostCategory") // Map ONLY POST Requests
    public @ResponseBody String addNewPostCategory(@RequestParam Integer post, @RequestParam Integer category) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        PostCategory p = new PostCategory();
        p.setPost(post);
        p.setCategory(category);
        postCategoryRepository.save(p);
        return "Saved";
    }

    @GetMapping(path = "/allPostCategory")
    public @ResponseBody Iterable<PostCategory> getAllPostCategory() {
        // This returns a JSON or XML with the users
        return postCategoryRepository.findAll();
    }
}